CREATE DATABASE IF NOT EXISTS `optimal`;
USE `optimal`;

CREATE TABLE `info` (
  `sr` int NOT NULL,
  `id` text NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NR1` int DEFAULT NULL,
  `NR2` int DEFAULT NULL,
  `NR3` int DEFAULT NULL,
  `NR4` int DEFAULT NULL,
  `NR5` int DEFAULT NULL,
  `AccNR1` float DEFAULT NULL,
  `AccNR2` float DEFAULT NULL,
  `AccNR3` float DEFAULT NULL,
  `AccNR4` float DEFAULT NULL,
  `AccNR5` float DEFAULT NULL,
  `TAccNR1` float DEFAULT NULL,
  `TAccNR2` float DEFAULT NULL,
  `TAccNR3` float DEFAULT NULL,
  `TAccNR4` float DEFAULT NULL,
  `TAccNR5` float DEFAULT NULL,
  `DNR1` time DEFAULT NULL,
  `DNR2` time DEFAULT NULL,
  `DNR3` time DEFAULT NULL,
  `DNR4` time DEFAULT NULL,
  `DNR5` time DEFAULT NULL,
  `R1` int DEFAULT NULL,
  `R2` int DEFAULT NULL,
  `R3` int DEFAULT NULL,
  `R4` int DEFAULT NULL,
  `R5` int DEFAULT NULL,
  `TAccR1` float DEFAULT NULL,
  `TAccR2` float DEFAULT NULL,
  `TAccR3` float DEFAULT NULL,
  `TAccR4` float DEFAULT NULL,
  `TAccR5` float DEFAULT NULL,
  `AccR1` float DEFAULT NULL,
  `AccR2` float DEFAULT NULL,
  `AccR3` float DEFAULT NULL,
  `AccR4` float DEFAULT NULL,
  `AccR5` float DEFAULT NULL,
  `DR1` time DEFAULT NULL,
  `DR2` time DEFAULT NULL,
  `DR3` time DEFAULT NULL,
  `DR4` time DEFAULT NULL,
  `DR5` time DEFAULT NULL,
  `O1` tinyint(1) DEFAULT NULL,
  `O2` tinyint(1) DEFAULT NULL,
  `O3` tinyint(1) DEFAULT NULL,
  `O4` tinyint(1) DEFAULT NULL,
  `O5` tinyint(1) DEFAULT NULL,
  `O6` tinyint(1) DEFAULT NULL,
  `O7` tinyint(1) DEFAULT NULL,
  `O8` tinyint(1) DEFAULT NULL,
  `O9` tinyint(1) DEFAULT NULL,
  `AccO1` float DEFAULT NULL,
  `AccO2` float DEFAULT NULL,
  `AccO3` float DEFAULT NULL,
  `AccO4` float DEFAULT NULL,
  `AccO5` float DEFAULT NULL,
  `AccO6` float DEFAULT NULL,
  `AccO7` float DEFAULT NULL,
  `AccO8` float DEFAULT NULL,
  `AccO9` float DEFAULT NULL,
  `TAccO1` float DEFAULT NULL,
  `TAccO2` float DEFAULT NULL,
  `TAccO3` float DEFAULT NULL,
  `TAccO4` float DEFAULT NULL,
  `TAccO5` float DEFAULT NULL,
  `TAccO6` float DEFAULT NULL,
  `TAccO7` float DEFAULT NULL,
  `TAccO8` float DEFAULT NULL,
  `TAccO9` float DEFAULT NULL,
  `DO1` time DEFAULT NULL,
  `DO2` time DEFAULT NULL,
  `DO3` time DEFAULT NULL,
  `DO4` time DEFAULT NULL,
  `DO5` time DEFAULT NULL,
  `DO6` time DEFAULT NULL,
  `DO7` time DEFAULT NULL,
  `DO8` time DEFAULT NULL,
  `DO9` time DEFAULT NULL,
  `PreInternal` int DEFAULT NULL,
  `PreExternal` int DEFAULT NULL,
  `score` int DEFAULT NULL
);
ALTER TABLE `info`
  ADD PRIMARY KEY (`sr`);

ALTER TABLE `info`
  MODIFY `sr` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
